name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

env:
  python-version: '3.10'
  project-name: dt-cli

jobs:

  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - run: pip install -r requirements.txt
      - run: make test
      - run: make lint

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        include:
          - os: ubuntu-latest
            platform-name: linux_amd64

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - run: pip install -r requirements.txt
      - run: make build
      - name: version
        run: echo "::set-output name=version::$(./dist/dt/dt --version)"
        id: version
      - name: Set archive name
        run: |
          ARCHIVE_NAME=dt-${{ steps.version.outputs.version }}-${{ matrix.platform-name }}
          echo "Archive name set to: $ARCHIVE_NAME"
          echo "archive-name=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Tar Linux and MacOS
        if: runner.os != 'Windows'
        run: |
          tar --format=ustar -czvf ${{ env.archive-name }}.tar.gz dist/*/
      - name: Archive Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive dist/*/ ${{ env.archive-name }}.zip

      - name: Generate Checksum
        run: |
          ARCHIVE_NAME=${{ env.archive-name }}
          md5sum $ARCHIVE_NAME.* > $ARCHIVE_NAME-checksum.md5

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: automated-builds
          path: ${{ env.archive-name }}.*
          retention-days: 7
          if-no-files-found: error

      - name: Upload Checksum Artifact
        uses: actions/upload-artifact@v2
        with:
          name: automated-builds
          path: ${{ env.archive-name }}-checksum.md5
          retention-days: 7
          if-no-files-found: error
