name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
  workflow_dispatch:

jobs:

  test_and_lint:
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Python ${{ matrix.python-version }} Setup
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Environment Setup
      run: make
    - name: Pytest
      run: make test
    - name: Lint and Type-Check
      run: make lint
  
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Python ${{ matrix.python-version }} Setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Distribution
      run: make build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: automated-builds
        path: dist/*
        retention-days: 7
        if-no-files-found: error

  test_dist:
    needs: build
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Python ${{ matrix.python-version }} Setup
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pull Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: automated-builds
          path: dist
      - name: Show Files
        run: ls -R
      - name: Install Wheel
        run: pip install dist/*.whl
      - name: Call CLI
        run: dt --version
